import { Header, HeaderType } from 'app/shared/constants';

export const BOOKS_HEADERS: Header[] = [
  {
    name: 'originalTitle',
    label: 'Original Title',
    type: HeaderType.TEXT,
    isVisible: true,
    hasSelect: false,
    isSelectAdd: false,
    sortDirection: null,
    rank: 1,
  },
  {
    name: 'title',
    label: 'Translated Title',
    type: HeaderType.TEXT,
    isVisible: true,
    hasSelect: false,
    isSelectAdd: false,
    sortDirection: null,
    rank: 2,
  },
  {
    name: 'author',
    label: 'Author',
    type: HeaderType.TEXT,
    isVisible: true,
    hasSelect: true,
    isSelectAdd: false,
    sortDirection: null,
    rank: 3,
  },
  {
    name: 'publicationDate',
    label: 'Publication Date',
    type: HeaderType.NUMBER,
    isVisible: true,
    hasSelect: false,
    isSelectAdd: false,
    sortDirection: null,
    rank: 4,
  },
  {
    name: 'language',
    label: 'Language',
    type: HeaderType.TEXT,
    isVisible: true,
    hasSelect: true,
    isSelectAdd: false,
    sortDirection: null,
    rank: 5,
  },
  {
    name: 'type',
    label: 'Type',
    type: HeaderType.TEXT,
    isVisible: true,
    hasSelect: true,
    isSelectAdd: false,
    sortDirection: null,
    rank: 6,
  },
  {
    name: 'category',
    label: 'Category',
    type: HeaderType.TEXT,
    isVisible: true,
    hasSelect: true,
    isSelectAdd: false,
    sortDirection: null,
    rank: 7,
  },
  {
    name: 'audience',
    label: 'Audience',
    type: HeaderType.TEXT,
    isVisible: true,
    hasSelect: true,
    isSelectAdd: false,
    sortDirection: null,
    rank: 8,
  },
  {
    name: 'status',
    label: 'Status',
    type: HeaderType.TEXT,
    isVisible: true,
    hasSelect: true,
    isSelectAdd: false,
    sortDirection: null,
    rank: 9,
  },
  {
    name: 'favorite',
    label: 'Favorite',
    type: HeaderType.TEXT,
    isVisible: true,
    hasSelect: true,
    isSelectAdd: false,
    sortDirection: null,
    rank: 10,
  }
];
